// Dart — hand-written tiered snippet bank (Practice mode).
// Same shape contract as python-bank.js.
//
// Deliberately NOT a 1:1 translation of the Python bank. Dart's actual
// finger/pattern friction lives in different places: null-safety operators
// (?, !, ??, ??=, late), the final/const distinction, named parameters with
// curly braces and required/defaults, cascades (..), arrow functions (=>),
// async/await with Future/Stream, and (at the top tier) Flutter widget
// trees, which are deeply nested and punctuation-heavy in a way Python
// rarely is.

export const tiers = [
  { name: "Warm-up", eyebrow: "Tier 1", required: 4, snippets: [
    { category: "core", chunks: ["int x = 5;"] },
    { category: "core", chunks: ['String name = "Ada";'] },
    { category: "core", chunks: ['print("hello world");'] },
    { category: "core", chunks: ["var total = a + b;"] },
    { category: "core", chunks: ["bool isReady = true;"] },
    { category: "core", chunks: ["final numbers = [1, 2, 3];"] },
    { category: "core", chunks: ['const person = {"name": "Ada"};'] },
    { category: "core", chunks: ["var length = items.length;"] },
    { category: "core", chunks: ["x += 1;"] },
    { category: "core", chunks: ["var squared = x * x;"] },
    { category: "core", chunks: ["double price = 19.99;"] },
    { category: "core", chunks: ["List<int> items = [];"] },
    { category: "core", chunks: ["bool isValid = false;"] },
    { category: "core", chunks: ["int count = 0;"] },
    { category: "core", chunks: ['String message = "done";'] },
    { category: "nullsafety", chunks: ["String? maybeName;"] },
    { category: "nullsafety", chunks: ["int age = maybeAge ?? 0;"] },
    { category: "nullsafety", chunks: ["late String token;"] },
    { category: "nullsafety", chunks: ["var value = maybeValue!;"] },
    { category: "collections", chunks: ["final Map<String, int> scores = {};"] },
    { category: "collections", chunks: ["final Set<String> tags = {};"] },
    { category: "imports", chunks: ["import 'dart:convert';"] },
    { category: "imports", chunks: ["import 'dart:async';"] },
  ]},
  { name: "Fluent", eyebrow: "Tier 2", required: 4, snippets: [
    { category: "core", chunks: ["final squares = [for (var n in nums) n * n];"] },
    { category: "core", chunks: ["final evens = nums.where((n) => n % 2 == 0).toList();"] },
    { category: "core", chunks: ["final total = values.fold(0, (a, b) => a + b);"] },
    { category: "core", chunks: ['final greeting = "Hello, $name!";'] },
    { category: "core", chunks: ["final maximum = a > b ? a : b;"] },
    { category: "core", chunks: ["final sortedItems = [...items]..sort();"] },
    { category: "core", chunks: ["final doubled = nums.map((n) => n * 2).toList();"] },
    { category: "core", chunks: ['final status = isReady ? "ready" : "waiting";'] },
    { category: "core", chunks: ["final [first, ...rest] = numbers;"] },
    { category: "core", chunks: ["final clean = value.trim().toLowerCase();"] },
    { category: "core", chunks: ["final isPalindrome = s == s.split('').reversed.join();"] },
    { category: "core", chunks: ["final hasDupes = nums.toSet().length != nums.length;"] },
    { category: "core", chunks: ["final reversedStr = s.split('').reversed.join();"] },
    { category: "core", chunks: ["final wordCount = text.split(' ').length;"] },
    { category: "core", chunks: ["final uniqueItems = items.toSet().toList();"] },
    { category: "core", chunks: ["final isSorted = nums.toList()..sort() == nums;"] },
    { category: "core", chunks: ["final common = setA.intersection(setB);"] },
    { category: "core", chunks: ["final longest = words.reduce((a, b) => a.length > b.length ? a : b);"] },
    { category: "core", chunks: ["final countTrue = items.where((x) => x).length;"] },
    { category: "core", chunks: ["final entries = map.entries.toList();"] },
    { category: "core", chunks: ["items.forEach((item) => print(item));"] },
    { category: "core", chunks: ["final anyNegative = nums.any((n) => n < 0);"] },
    { category: "core", chunks: ["final allPositive = nums.every((n) => n > 0);"] },
    { category: "core", chunks: ["final firstMatch = items.firstWhere((x) => x.isActive);"] },
    { category: "nullsafety", chunks: ["final trimmed = text?.trim() ?? '';"] },
    { category: "nullsafety", chunks: ["config ??= defaultConfig;"] },
    { category: "nullsafety", chunks: ["final len = value?.length ?? 0;"] },
    { category: "nullsafety", chunks: ["user?.updateProfile();"] },
    { category: "nullsafety", chunks: ["if (value != null) print(value);"] },
    { category: "params", chunks: ["void greet({required String name}) {}"] },
    { category: "params", chunks: ["void greet({String name = 'friend'}) {}"] },
    { category: "params", chunks: ["void move(int x, [int y = 0]) {}"] },
    { category: "params", chunks: ["const Widget child;"] },
    { category: "cascades", chunks: ["buffer\n  ..write('a')\n  ..write('b');"] },
    { category: "cascades", chunks: ["controller\n  ..text = 'hi'\n  ..selection = sel;"] },
    { category: "async", chunks: ["Future<int> fetchCount() async => 5;"] },
    { category: "async", chunks: ["final data = await fetchData();"] },
    { category: "async", chunks: ["final results = await Future.wait(futures);"] },
    { category: "async", chunks: ["Stream<int> countUp() async* {}"] },
    { category: "collections", chunks: ["final grouped = groupBy(items, (i) => i.type);"] },
    { category: "collections", chunks: ["final byId = {for (var u in users) u.id: u};"] },
    { category: "collections", chunks: ["final flat = nested.expand((x) => x).toList();"] },
    { category: "json", chunks: ["final data = jsonDecode(raw);"] },
    { category: "json", chunks: ["final text = jsonEncode(data);"] },
    { category: "validation", chunks: ["assert(value is int);"] },
    { category: "validation", chunks: ["if (value is! String) throw ArgumentError('expected String');"] },
  ]},
  { name: "Compound", eyebrow: "Tier 3", required: 4, snippets: [
    { category: "core", chunks: ["final pairs = Map.fromIterables(keys, values);"] },
    { category: "core", chunks: ["final matrix = [for (var i = 0; i < 3; i++) [for (var j = 0; j < 3; j++) i * j]];"] },
    { category: "core", chunks: ["final filtered = data.where((x) => x['active'] == true).toList();"] },
    { category: "core", chunks: ["final result = items.firstWhere((x) => x > 0, orElse: () => -1);"] },
    { category: "core", chunks: ["final combined = {...baseConfig, ...overrides};"] },
    { category: "core", chunks: ["final names = [...people]..sort((a, b) => a.name.compareTo(b.name));"] },
    { category: "core", chunks: ["final flat = [for (var row in matrix) ...row];"] },
    { category: "core", chunks: ["final cleaned = lines.map((s) => s.trim()).where((s) => s.isNotEmpty).toList();"] },
    { category: "core", chunks: ["final transposed = List.generate(cols, (c) => [for (var row in matrix) row[c]]);"] },
    { category: "core", chunks: ["final deduped = items.toSet().toList();"] },
    { category: "core", chunks: ["final wordLengths = {for (var w in text.split(' ')) w: w.length};"] },
    { category: "core", chunks: ["final chunks = [for (var i = 0; i < items.length; i += 3) items.sublist(i, min(i + 3, items.length))];"] },
    { category: "core", chunks: ["final nestedGet = (data['user'] as Map?)?['name'] ?? 'unknown';"] },
    { category: "core", chunks: ["final safeDiv = b != 0 ? a / b : 0;"] },
    { category: "core", chunks: ["final clamped = value.clamp(0, 100);"] },
    { category: "core", chunks: ["final merged = [...a, ...b]..sort();"] },
    { category: "core", chunks: ["final indexMap = {for (var (i, v) in items.indexed) v: i};"] },
    { category: "core", chunks: ["final validRows = table.where((row) => row.every((c) => c != null)).toList();"] },
    { category: "core", chunks: ["final topN = (scores.entries.toList()..sort((a, b) => b.value.compareTo(a.value))).take(3);"] },
    { category: "core", chunks: ["final windowed = [for (var i = 0; i < nums.length - 1; i++) [nums[i], nums[i + 1]]];"] },
    { category: "core", chunks: ["final (min, max) = (nums.reduce(math.min), nums.reduce(math.max));"] },
    { category: "core", chunks: ["switch (status) {\n  case Status.active:\n    return 'on';\n  default:\n    return 'off';\n}"] },
    { category: "nullsafety", chunks: ["final name = user?.profile?.displayName ?? 'Guest';"] },
    { category: "nullsafety", chunks: ["T requireNonNull<T>(T? value) => value ?? (throw StateError('null value'));"] },
    { category: "nullsafety", chunks: ["if (result case Success(:final data)) print(data);"] },
    { category: "params", chunks: ["Widget build({required BuildContext context, Key? key}) {\n  return Container();\n}"] },
    { category: "cascades", chunks: ["final list = <int>[]\n  ..add(1)\n  ..add(2)\n  ..sort();"] },
    { category: "async", chunks: ["try {\n  final data = await fetchData();\n} on TimeoutException {\n  data = null;\n}"] },
    { category: "async", chunks: ["final stream = source.where((e) => e.isValid).map((e) => e.value);"] },
    { category: "async", chunks: ["await for (final chunk in stream) {\n  process(chunk);\n}"] },
    { category: "async", chunks: ["unawaited(logEvent('opened'));"] },
    { category: "regex", chunks: ['final match = RegExp(r"\\d+").firstMatch(text);'] },
    { category: "regex", chunks: ['final digits = RegExp(r"\\d+").allMatches(text).map((m) => m.group(0));'] },
    { category: "regex", chunks: ['final cleaned = text.replaceAll(RegExp(r"\\s+"), " ");'] },
    { category: "json", chunks: ["final parsed = [for (var line in lines) jsonDecode(line)];"] },
    { category: "json", chunks: ["final version = (data['meta'] as Map?)?['version'] ?? 'unknown';"] },
    { category: "validation", chunks: ["final errors = [for (var (field, msg) in checks) if (field.isEmpty) msg];"] },
    { category: "validation", chunks: ["final isValidRange = value >= 0 && value <= 100;"] },
    { category: "collections", chunks: ["final counts = <String, int>{}..addEntries(items.map((i) => MapEntry(i, 1)));"] },
  ]},
  { name: "Composed", eyebrow: "Tier 4", required: 3, snippets: [
    { category: "core", chunks: ["int add(int a, int b) {\n  return a + b;\n}"] },
    { category: "core", chunks: ["for (final item in items) {\n  print(item);\n}"] },
    { category: "core", chunks: ["bool isEven(int n) => n % 2 == 0;"] },
    { category: "core", chunks: ["while (count < limit) {\n  count++;\n}"] },
    { category: "core", chunks: ["var total = 0;\nfor (final n in numbers) {\n  total += n;\n}"] },
    { category: "core", chunks: ["final file = File('data.txt');\nfinal lines = await file.readAsLines();"] },
    { category: "core", chunks: ["final squares = <int>[];\nfor (var n = 0; n < 5; n++) {\n  squares.add(n * n);\n}"] },
    { category: "core", chunks: ["int square(int n) => n * n;"] },
    { category: "core", chunks: ["String grade;\nif (score >= 90) {\n  grade = 'A';", "} else {\n  grade = 'B';\n}"] },
    { category: "core", chunks: ["int value;\ntry {\n  value = int.parse(text);", "} on FormatException {\n  value = 0;\n}"] },
    { category: "core", chunks: ["int factorial(int n) {\n  if (n == 0) return 1;", "  return n * factorial(n - 1);\n}"] },
    { category: "core", chunks: ["class Point {\n  final double x;\n  final double y;", "  Point(this.x, this.y);\n}"] },
    { category: "core", chunks: ["bool isPrime(int n) {\n  if (n < 2) return false;", "  return List.generate(n - 2, (i) => i + 2).every((i) => n % i != 0);\n}"] },
    { category: "core", chunks: ["final stack = <int>[];\nstack.add(1);\nstack.removeLast();"] },
    { category: "core", chunks: ["String greet([String name = 'friend']) => 'Hi, \$name';"] },
    { category: "core", chunks: ["final nums = [1, 2, 3];\nnums.add(4);\nnums.remove(2);"] },
    { category: "core", chunks: ["void countdown(int n) {\n  while (n > 0) {", "    print(n);\n    n--;\n  }\n}"] },
    { category: "core", chunks: ["for (var i = 0; i < 3; i++) {\n  for (var j = 0; j < 3; j++) {\n    print('\$i \$j');\n  }\n}"] },
    { category: "core", chunks: ["int sumList(List<int> nums) {\n  if (nums.isEmpty) return 0;", "  return nums.first + sumList(nums.sublist(1));\n}"] },
    { category: "core", chunks: ["final data = <String, String>{};\ndata['key'] = 'value';\ndata.remove('key');"] },
    { category: "core", chunks: ["int fib(int n) {\n  if (n <= 1) return n;", "  return fib(n - 1) + fib(n - 2);\n}"] },
    { category: "core", chunks: ["final file = File('out.txt');\nawait file.writeAsString('done');"] },
    { category: "core", chunks: ["bool isValidEmail(String s) => s.contains('@') && s.contains('.');"] },
    { category: "core", chunks: ["final queue = <int>[];\nqueue.add(1);\nqueue.removeAt(0);"] },
    { category: "core", chunks: ["for (final entry in data.entries) {\n  print('\${entry.key}: \${entry.value}');\n}"] },
    { category: "oop", chunks: ["abstract class Shape {\n  double area();\n}"] },
    { category: "oop", chunks: ["class Circle extends Shape {\n  final double radius;\n  Circle(this.radius);", "  @override\n  double area() => 3.14159 * radius * radius;\n}"] },
    { category: "oop", chunks: ["mixin Flyable {\n  void fly() => print('flying');\n}"] },
    { category: "oop", chunks: ["class Bird with Flyable {\n  String name = 'sparrow';\n}"] },
    { category: "oop", chunks: ["class Singleton {\n  Singleton._();\n  static final instance = Singleton._();\n}"] },
    { category: "async", chunks: ["Future<String> loadUser(String id) async {\n  final res = await api.get('/users/\$id');", "  return res.body;\n}"] },
    { category: "async", chunks: ["Future<void> retry(Future<void> Function() task, {int times = 3}) async {\n  for (var i = 0; i < times; i++) {", "    try {\n      await task();\n      return;\n    } catch (_) {}\n  }\n}"] },
    { category: "regex", chunks: ["bool isValidPhone(String s) {\n  return RegExp(r'^\\d{3}-\\d{3}-\\d{4}\$').hasMatch(s);\n}"] },
    { category: "regex", chunks: ["String slugify(String s) {\n  return s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '-');\n}"] },
    { category: "json", chunks: ["Map<String, dynamic> loadJson(String path) {\n  final raw = File(path).readAsStringSync();", "  return jsonDecode(raw);\n}"] },
    { category: "json", chunks: ["void saveJson(Map<String, dynamic> data, String path) {\n  File(path).writeAsStringSync(jsonEncode(data));\n}"] },
    { category: "validation", chunks: ["void validateAge(int age) {\n  if (age < 0) {\n    throw ArgumentError('age must be non-negative');\n  }\n}"] },
    { category: "widgets", chunks: ["Widget build(BuildContext context) {\n  return Text('Hello');\n}"] },
    { category: "widgets", chunks: ["Widget build(BuildContext context) {\n  return Column(\n    children: [Text('A'), Text('B')],\n  );\n}"] },
    { category: "widgets", chunks: ["Widget build(BuildContext context) {\n  return Padding(\n    padding: const EdgeInsets.all(8.0),", "    child: Text('Hi'),\n  );\n}"] },
    { category: "widgets", chunks: ["Widget build(BuildContext context) {\n  return ElevatedButton(\n    onPressed: () {},\n    child: Text('Tap'),\n  );\n}"] },
    { category: "widgets", chunks: ["Widget build(BuildContext context) {\n  return ListView.builder(\n    itemCount: items.length,", "    itemBuilder: (context, i) => Text(items[i]),\n  );\n}"] },
  ]},
];
