// Python — hand-written tiered snippet bank (Practice mode).
//
// Shape contract (shared by every language bank and every generative pool):
//   export const tiers = [
//     { name, eyebrow, required, snippets: [{ category, chunks: [string, ...] }] },
//     ...
//   ];
// `category` is tracked in stats but never shown in the UI — reserved for a
// future per-category insights breakdown. `chunks` lets a snippet be typed
// as several parts in sequence (used for multi-line composed examples).

export const tiers = [
  { name: "Warm-up", eyebrow: "Tier 1", required: 4, snippets: [
    { category: "core", chunks: ["x = 5"] },
    { category: "core", chunks: ['name = "Ada"'] },
    { category: "core", chunks: ['print("hello world")'] },
    { category: "core", chunks: ["total = a + b"] },
    { category: "core", chunks: ["is_ready = True"] },
    { category: "core", chunks: ["numbers = [1, 2, 3]"] },
    { category: "core", chunks: ['person = {"name": "Ada"}'] },
    { category: "core", chunks: ["length = len(items)"] },
    { category: "core", chunks: ["x += 1"] },
    { category: "core", chunks: ["squared = x ** 2"] },
    { category: "core", chunks: ["price = 19.99"] },
    { category: "core", chunks: ["items = []"] },
    { category: "core", chunks: ["is_valid = False"] },
    { category: "core", chunks: ["count = 0"] },
    { category: "core", chunks: ['message = "done"'] },
    { category: "regex", chunks: ["import re"] },
    { category: "strings", chunks: ['parts = line.split(",")'] },
    { category: "files", chunks: ["import os"] },
    { category: "json", chunks: ["import json"] },
  ]},
  { name: "Fluent", eyebrow: "Tier 2", required: 4, snippets: [
    { category: "core", chunks: ["squares = [n * n for n in range(10)]"] },
    { category: "core", chunks: ["evens = [n for n in nums if n % 2 == 0]"] },
    { category: "core", chunks: ["total = sum(x for x in values)"] },
    { category: "core", chunks: ['greeting = f"Hello, {name}!"'] },
    { category: "core", chunks: ["maximum = max(a, b, key=abs)"] },
    { category: "core", chunks: ["sorted_items = sorted(items, reverse=True)"] },
    { category: "core", chunks: ["doubled = list(map(lambda x: x * 2, nums))"] },
    { category: "core", chunks: ['status = "ready" if is_ready else "waiting"'] },
    { category: "core", chunks: ["first, *rest = numbers"] },
    { category: "core", chunks: ["clean = value.strip().lower()"] },
    { category: "core", chunks: ["is_palindrome = s == s[::-1]"] },
    { category: "core", chunks: ["has_dupes = len(set(nums)) != len(nums)"] },
    { category: "core", chunks: ["is_anagram = sorted(a) == sorted(b)"] },
    { category: "core", chunks: ["majority = max(set(nums), key=nums.count)"] },
    { category: "core", chunks: ["reversed_str = s[::-1]"] },
    { category: "core", chunks: ["word_count = len(text.split())"] },
    { category: "core", chunks: ['vowels = sum(1 for c in s if c in "aeiou")'] },
    { category: "core", chunks: ["unique_items = list(set(items))"] },
    { category: "core", chunks: ["is_sorted = nums == sorted(nums)"] },
    { category: "core", chunks: ["digit_sum = sum(int(d) for d in str(n))"] },
    { category: "core", chunks: ["common = set(a) & set(b)"] },
    { category: "core", chunks: ["missing = set(range(n)) - set(nums)"] },
    { category: "core", chunks: ['capitalized = " ".join(w.capitalize() for w in s.split())'] },
    { category: "core", chunks: ["char_freq = {c: s.count(c) for c in set(s)}"] },
    { category: "core", chunks: ['is_pangram = set("abcdefghijklmnopqrstuvwxyz") <= set(s.lower())'] },
    { category: "core", chunks: ["running_total = [sum(nums[:i+1]) for i in range(len(nums))]"] },
    { category: "core", chunks: ["swapped = {v: k for k, v in d.items()}"] },
    { category: "core", chunks: ["longest = max(words, key=len)"] },
    { category: "core", chunks: ["count_true = sum(bool(x) for x in items)"] },
    { category: "core", chunks: ["flat_pairs = [(k, v) for k, v in d.items()]"] },
    { category: "regex", chunks: ['match = re.search(r"\\d+", text)'] },
    { category: "regex", chunks: ['digits = re.findall(r"\\d+", text)'] },
    { category: "regex", chunks: ['cleaned = re.sub(r"\\s+", " ", text)'] },
    { category: "regex", chunks: ['words = re.split(r"[,;]\\s*", text)'] },
    { category: "regex", chunks: ['has_number = bool(re.search(r"\\d", s))'] },
    { category: "strings", chunks: ["tokens = text.lower().split()"] },
    { category: "strings", chunks: ['joined = "-".join(parts)'] },
    { category: "strings", chunks: ["padded = str(n).zfill(4)"] },
    { category: "strings", chunks: ['trimmed = " ".join(s.split())'] },
    { category: "strings", chunks: ["title_case = s.title()"] },
    { category: "files", chunks: ["exists = os.path.exists(path)"] },
    { category: "files", chunks: ["full_path = os.path.join(folder, filename)"] },
    { category: "files", chunks: ["base = os.path.basename(path)"] },
    { category: "datetime", chunks: ["now = datetime.now()"] },
    { category: "datetime", chunks: ["today = date.today()"] },
    { category: "datetime", chunks: ['formatted = now.strftime("%Y-%m-%d")'] },
    { category: "datetime", chunks: ['parsed = datetime.strptime(text, "%Y-%m-%d")'] },
    { category: "json", chunks: ["data = json.loads(raw)"] },
    { category: "json", chunks: ["text = json.dumps(data)"] },
    { category: "json", chunks: ["pretty = json.dumps(data, indent=2)"] },
    { category: "validation", chunks: ["assert isinstance(value, int)"] },
    { category: "validation", chunks: ['if not isinstance(x, str): raise TypeError("expected str")'] },
    { category: "validation", chunks: ['raise ValueError(f"invalid input: {value}")'] },
  ]},
  { name: "Compound", eyebrow: "Tier 3", required: 4, snippets: [
    { category: "core", chunks: ["pairs = {k: v for k, v in zip(keys, values)}"] },
    { category: "core", chunks: ["matrix = [[i * j for j in range(3)] for i in range(3)]"] },
    { category: "core", chunks: ['filtered = [x for x in data if x.get("active")]'] },
    { category: "core", chunks: ["result = next((x for x in items if x > 0), None)"] },
    { category: "core", chunks: ["combined = {**base_config, **overrides}"] },
    { category: "core", chunks: ["names = sorted(people, key=lambda p: p.name)"] },
    { category: "core", chunks: ["if (n := len(data)) > 10:\n    print(n)"] },
    { category: "core", chunks: ["flat = [x for row in matrix for x in row]"] },
    { category: "core", chunks: ["cleaned = [s.strip() for s in lines if s.strip()]"] },
    { category: "core", chunks: ['total = sum(v for k, v in scores.items() if k != "bonus")'] },
    { category: "core", chunks: ["grouped = {k: [v for v in values if v.type == k] for k in types}"] },
    { category: "core", chunks: ["transposed = list(zip(*matrix))"] },
    { category: "core", chunks: ["deduped = list(dict.fromkeys(items))"] },
    { category: "core", chunks: ["two_sum_pairs = [(a, b) for a in nums for b in nums if a + b == target and a != b]"] },
    { category: "core", chunks: ["word_lengths = {w: len(w) for w in text.split()}"] },
    { category: "core", chunks: ["chunks = [items[i:i+3] for i in range(0, len(items), 3)]"] },
    { category: "core", chunks: ["counts = {x: nums.count(x) for x in set(nums)}"] },
    { category: "core", chunks: ['nested_get = data.get("user", {}).get("name", "unknown")'] },
    { category: "core", chunks: ["filtered_sorted = sorted((x for x in data if x > 0), reverse=True)"] },
    { category: "core", chunks: ['anagram_groups = {"".join(sorted(w)): w for w in words}'] },
    { category: "core", chunks: ["safe_div = a / b if b != 0 else 0"] },
    { category: "core", chunks: ["clamped = max(0, min(value, 100))"] },
    { category: "core", chunks: ['is_balanced = s.count("(") == s.count(")")'] },
    { category: "core", chunks: ["merged = sorted(list(a) + list(b))"] },
    { category: "core", chunks: ["running_max = [max(nums[:i+1]) for i in range(len(nums))]"] },
    { category: "core", chunks: ["index_map = {v: i for i, v in enumerate(items)}"] },
    { category: "core", chunks: ["valid_rows = [row for row in table if all(row)]"] },
    { category: "core", chunks: ["top_n = sorted(scores, key=scores.get, reverse=True)[:3]"] },
    { category: "core", chunks: ["windowed = [nums[i:i+2] for i in range(len(nums) - 1)]"] },
    { category: "core", chunks: ['reversed_words = " ".join(reversed(s.split()))'] },
    { category: "regex", chunks: ['groups = re.match(r"(\\d{3})-(\\d{4})", phone).groups()'] },
    { category: "regex", chunks: ['stripped = re.sub(r"[^a-zA-Z0-9]", "", s)'] },
    { category: "regex", chunks: ['all_matches = [m.group() for m in re.finditer(r"\\w+", text)]'] },
    { category: "regex", chunks: ['is_valid = bool(re.match(r"^[A-Za-z]+$", word))'] },
    { category: "regex", chunks: ['snake_case = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()'] },
    { category: "regex", chunks: ['domain = re.search(r"https?://([^/]+)", url).group(1)'] },
    { category: "strings", chunks: ["char_counts = collections.Counter(text)"] },
    { category: "strings", chunks: ['reversed_sentence = " ".join(word[::-1] for word in s.split())'] },
    { category: "files", chunks: ["name, ext = os.path.splitext(filename)"] },
    { category: "files", chunks: ['json_files = [f for f in os.listdir(folder) if f.endswith(".json")]'] },
    { category: "datetime", chunks: ["age_days = (date.today() - birth_date).days"] },
    { category: "datetime", chunks: ["next_week = today + timedelta(days=7)"] },
    { category: "json", chunks: ["parsed = [json.loads(line) for line in lines]"] },
    { category: "json", chunks: ['nested_value = data.get("meta", {}).get("version", "unknown")'] },
    { category: "validation", chunks: ["errors = [msg for field, msg in checks if not field]"] },
    { category: "validation", chunks: ["is_valid_range = 0 <= value <= 100"] },
  ]},
  { name: "Composed", eyebrow: "Tier 4", required: 3, snippets: [
    { category: "core", chunks: ["def add(a, b):\n    return a + b"] },
    { category: "core", chunks: ["for item in items:\n    print(item)"] },
    { category: "core", chunks: ["def is_even(n):\n    return n % 2 == 0"] },
    { category: "core", chunks: ["while count < limit:\n    count += 1"] },
    { category: "core", chunks: ["total = 0\nfor n in numbers:\n    total += n"] },
    { category: "core", chunks: ['with open("data.txt") as f:\n    lines = f.readlines()'] },
    { category: "core", chunks: ["squares = []\nfor n in range(5):\n    squares.append(n * n)"] },
    { category: "core", chunks: ["def square(n):\n    return n * n"] },
    { category: "core", chunks: ['if score >= 90:\n    grade = "A"', 'else:\n    grade = "B"'] },
    { category: "core", chunks: ["try:\n    value = int(text)", "except ValueError:\n    value = 0"] },
    { category: "core", chunks: ["def factorial(n):\n    if n == 0:\n        return 1", "    return n * factorial(n - 1)"] },
    { category: "core", chunks: ["class Point:\n    def __init__(self, x, y):", "        self.x = x\n        self.y = y"] },
    { category: "core", chunks: ["def is_prime(n):\n    if n < 2:\n        return False", "    return all(n % i for i in range(2, n))"] },
    { category: "core", chunks: ["stack = []\nstack.append(1)\nstack.pop()"] },
    { category: "core", chunks: ['def greet(name="friend"):\n    return f"Hi, {name}"'] },
    { category: "core", chunks: ["nums = [1, 2, 3]\nnums.append(4)\nnums.remove(2)"] },
    { category: "core", chunks: ["def countdown(n):\n    while n > 0:", "        print(n)\n        n -= 1"] },
    { category: "core", chunks: ["for i in range(3):\n    for j in range(3):\n        print(i, j)"] },
    { category: "core", chunks: ["def sum_list(nums):\n    if not nums:\n        return 0", "    return nums[0] + sum_list(nums[1:])"] },
    { category: "core", chunks: ['data = {}\ndata["key"] = "value"\ndel data["key"]'] },
    { category: "core", chunks: ["def fib(n):\n    if n <= 1:\n        return n", "    return fib(n - 1) + fib(n - 2)"] },
    { category: "core", chunks: ['with open("out.txt", "w") as f:\n    f.write("done")'] },
    { category: "core", chunks: ['def is_valid_email(s):\n    return "@" in s and "." in s'] },
    { category: "core", chunks: ["queue = []\nqueue.append(1)\nqueue.pop(0)"] },
    { category: "core", chunks: ["for key, value in data.items():\n    print(key, value)"] },
    { category: "regex", chunks: ['pattern = re.compile(r"\\d+")\nmatches = pattern.findall(text)'] },
    { category: "regex", chunks: ['def is_valid_phone(s):\n    return bool(re.match(r"^\\d{3}-\\d{3}-\\d{4}$", s))'] },
    { category: "regex", chunks: ['def slugify(s):\n    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")'] },
    { category: "strings", chunks: ["def word_frequencies(text):\n    words = text.lower().split()\n    return {w: words.count(w) for w in set(words)}"] },
    { category: "files", chunks: ["def read_lines(path):\n    with open(path) as f:\n        return f.readlines()"] },
    { category: "files", chunks: ["for root, dirs, files in os.walk(folder):\n    print(root)"] },
    { category: "datetime", chunks: ["def days_until(target_date):\n    return (target_date - date.today()).days"] },
    { category: "json", chunks: ["def load_json(path):\n    with open(path) as f:\n        return json.load(f)"] },
    { category: "json", chunks: ['def save_json(data, path):\n    with open(path, "w") as f:\n        json.dump(data, f)'] },
    { category: "validation", chunks: ['def validate_age(age):\n    if age < 0:\n        raise ValueError("age must be non-negative")'] },
    { category: "validation", chunks: ["def require_keys(data, keys):\n    for key in keys:", "        if key not in data:\n            raise KeyError(key)"] },
  ]},
];
